### ISSUE TITLE
Add Zenodo DOI

### ISSUE THREAD

**Issue by matthewfeickert** [hsf-training/pyhep_python_libraries#5]
For these sorts of (very nice) resource lists I think it is nice to have a [Zenodo DOI](http://help.zenodo.org/features/) for them.

For reference, c.f. 
- The [Issue that added one](https://github.com/iml-wg/HEP-ML-Resources/issues/19) for [IML HEPML Resources](https://github.com/iml-wg/HEP-ML-Resources)
- The [IML HEPML Resources Zenodo archive](https://zenodo.org/record/1173019#.W5vO7N0zZhE) (probably in need of a new release soon)

**Comment by tunnell** [comment]
Good idea.  For other projects (i.e. code projects), this hook gets triggered by a release through Github website. I'm not sure if there are other ways to trigger. Do you trigger it each commit (is version then commit ID?)?  Otherwise, we might need to version the whole set of pages, which may not be a bad idea anyways.

**Comment by matthewfeickert** [comment]
It is triggered through creating a release for the specific repo. I don't think you actually need to use GitHub's UX to do so, I think any Git tag will do. The web UX just is more suggestive of the good practice of semantic versioning.

**Comment by tunnell** [comment]
I didn't think any git tag would work (at least on other project).  Adding Zenodo now.  Added OAuth access to the Github organization.   DOI: 10.5281/zenodo.1420445

**Comment by matthewfeickert** [comment]
Looks good! I see that Zenodo is building the archive now at [![DOI](https://zenodo.org/badge/144829348.svg)](https://zenodo.org/badge/latestdoi/144829348). :+1:
